version: '3.6'
services:
  app:
    build: .
    ports:
      - 3001:3001
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: city_bike_hel
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ${RAW_CSV_PATH}:/var/rawData
volumes:
  db-data:
